from pyb import Pin, ExtInt
import time

def callback(line):
    print("Interrupt triggered on line:", line)

# Configure external interrupt on pin PA0
ext_int = ExtInt(Pin('PC13'), ExtInt.IRQ_RISING, Pin.PULL_NONE, callback)

while True:
    print("Waiting for interrupt...")
    time.sleep(1)

"""
(venv) PS C:\Users\vlab\PycharmProjects\MicroPython_codes> ampy --port COM7 run .\External_interrupts.py      
Waiting for interrupt...
Waiting for interrupt...
Waiting for interrupt...
Waiting for interrupt...
Interrupt triggered on line: 13
Waiting for interrupt...
Waiting for interrupt...
Interrupt triggered on line: 13
Waiting for interrupt...
Interrupt triggered on line: 13
Waiting for interrupt...
Interrupt triggered on line: 13
Waiting for interrupt...
Interrupt triggered on line: 13
Waiting for interrupt...
Interrupt triggered on line: 13
Waiting for interrupt...

Aborted!
"""